/**
 * Single source of truth for product options used across the app.
 * Used in: Service Agreement forms, HyTrack form, Add/Edit Run dialogs.
 */
export const DEFAULT_PRODUCTS = [
  "Auto gel hand Sanitiser with stand",
  "1.4Lt Sharp unit",
  "1.4ltr Sharp - Bracket / Mounting Frame",
  "1.4Ltr Sharp (with metal Container)",
  "8Ltr sharp unit",
  "Admin Fee",
  "Air Freshener",
  "Air Freshener - AIROMA",
  "Air freshener (Odour Neutralizer)",
  "Air Freshener Cans",
  "Ash Trays  (Client Own)",
  "Auto Paper towels 1Ply white",
  "Auto towel Dispenser (hygiene system",
  "Bactisan 300ml DISP.",
  "Bactisan Refills - 300ml",
  "Body wash",
  "Deb 1 Litre  soap Cartridge",
  "EJ-300 Jumbo Roll Dispenser - (stainless Steel)",
  "EnMotion Electric Hand-towel Disp.",
  "EnMotion Handtowel Refills (6/Ctn)",
  "ET-500 Paper Towel Dispenser (marble)",
  "GEL Unit with Timer  - (AF190M)",
  "Hand Dryer - E05 Model",
  "Hand Dryer - M88A Plus Style",
  "Hand Sanitiser AUTO",
  "Hand Sanitiser AUTO GEL Refill",
  "Hand Sanitiser Disp. 300ml",
  "Hand Sanitiser MANUAL GEL Bottle",
  "Hand Sanitizer Manual",
  "Hand Sanitser Pedestal",
  "Hand Soap Auto (1 Ltr Sensor)",
  "Hand Soap- Refill",
  "Hand-Dryer - IAM model",
  "Hand-Dryer - IAM model (+ Filter & Fragrance)",
  "Hand-Dryer - IAM model (+ Filter only)",
  "IAM H/Dryer - Fragrance Blocks",
  "IAM H/Dyrer - FILTER",
  "Interfold Paper Hand Towel",
  "Jumbo Toilet Tissue - 2ply (Crtn of 8)",
  "Jumboroll Linea Dispenser (hygiene system)",
  "KEY SERVICE",
  "MATs - US / Fragrant",
  "MATS (1/2's) - US / Fragrant",
  "Maxithins Sanitary Napkins",
  "Medical Bin (Lrg)",
  "Medical Bin (Medium)",
  "Medical Bin (sml)",
  "Multifold Paper Hand Towel (Z-Fold)",
  "Multifold Papertowel Dispencer ( VDA )",
  "Nappy Bin (Flat top) - Medium",
  "Nappy Bin (Medium)",
  "Nappy Bin (Sml)",
  "Nappy Bins (Lrg)",
  "Pysect",
  "Safe Seat Dispenser (TSS)",
  "Sani WIPE Dispencer",
  "Sanitary Bins - Basic  (grey)",
  "Sanitary Bins - Basic  (Switch)",
  "Sanitary Bins - O/S White",
  "Sanitary bins - PEDAL Style",
  "Sanitary Bins - SENSOR Type",
  "Sanitary Bins - SENSOR Type (O/S)",
  "Sanitary Bins - SENSOR Type BLACK",
  "Sanitary Bins - Touch Free o/s (white) Abco",
  "SANITEX 800ml - ANTI-BAC Soap (6 Pkt)",
  "SANITEX 800ml - FOAM Soap (6 Pkt)",
  "SANITEX 800ml - LIQUID Soap (6 Pkt)",
  "Sanitex ANIT-BAC Soap Disp",
  "Sanitex FOAM Soap Disp",
  "Sanitex FOAM Soap Disp- re-fillable",
  "Sanitex HAND Soap Disp",
  "Sanitex HAND Soap Disp - Refillable",
  "SARAYA  Manual Hand Sanitiser 1.2L",
  "Saraya Auto Hand sanitzier 1.2L.",
  "SARAYA Hand Sanitizer - Auto Disp. (1ltr)",
  "SARAYA Hand Sanitizer- Alcohol free Manual",
  "SARAYA Hand sanitizing Manual Disp. (1ltr)",
  "Smart San Hand Sani Solution - (3ltr Bottle)",
  "Smart San Hand Sani Solution - (5ltr Bottle) Ctn of 2",
  "Soap - REFILLS ONLY",
  "Soap cartridge foam refill 1L",
  "Soap Dispenser  (Bobson - 1.7Ltr)",
  "Soap Dispenser  (Bobson - 900ml)",
  "Soap Dispenser (4 Ltr)( Blue soap)",
  "Soap Dispenser + refill",
  "Soap: WHITE (5ltr Bottle)",
  "Stainless Steel HORIZONTAL Soap Dispencer",
  "Stainless Steel Triple Toilet Roll Dispencer",
  "Suprega Grit Disp. (4Ltr)",
  "Suprega Plus 4 ltr GRIT Cartridge",
  "Tampax Tampons",
  "Toilet Paper - HS 700",
  "Toilet Paper Rolls Single (box of 48)",
  "Toilet Roll Holder (Reserved Roll )",
  "Toilet Seat Spray Disp With Bottle refill",
  "Toilet Seat Spray Disp.",
  "Toilet Seat Sprays - (Take-a-seat / Have-A-Seat) REFILLS (300ml)",
  "Urinal Crystals",
  "Urinal Sanitiser - External Disp",
  "Urinal Sanitizers - Internal",
  "Urinal Sanitizing Blocks - ∆",
  "Urinal Sanitizing Blocks - DOME style",
  "Urinal Spray",
  "Urinal Treatment (D/C)",
  "Vending Machine",
  "WC Descale",
  "WC Sanitizers - Glass (internal)",
  "WC Sanitizers - internal",
  "WC Treatment ( D/C )",
  "white soap 4 Ltr",
];
